### PR TITLE
[1.19.2] Persistently save XP saves for entities

### LINKED ISSUE #19: [1.19.2] XP Stats are not presistently saved
Sortilege saves XP stats of a living entity to a static map `XPHelper.XP_STATS`. While this is fine, this map is never persistently saved. So if die, click on "Title Screen", then close the game (or crash), when you reload the world the `ModEvents.xpRefill` event listener fails with a null pointer, since the XP stat it's trying to get doesn't exist for the UUID you saved it for.

The 1.19.2 version is written in Forge, so this can easily be solved by making a LivingEntity capability and attaching XP stats to it (this can even work with Players, but you'd need to watch out for this issue: MinecraftForge/MinecraftForge#9311). Even though the 1.20.1 version is written in Fabric, I'm sure there is some sort of similar solution to persistently save XP stats.

In any case, it's not a high priority issue since players will usually immediately respawn after their death, but it's something to point out. It's probably the root cause for issue #12.

### PR DESCRIPTION
**Pull request by Jonathing**
This PR adds a forge capability to replace `XPHelper.XP_SAVES`. This allows for XP stats saved by Sortilege to also be saved to disk, eliminating the root cause of various XP loss issues.

Additionally, `.gitignore` and `.gitattributes` files were added to streamline the process of comitting files to the repository. Also, a small closure was added to the buildscript to assist with IntelliJ IDEA refusing to download linked source and javadoc files.

- Fixes #19.
- Effectively supersedes #13.

### CODE REVIEW

File: src/main/java/net/lyof/sortilege/capabilities/ModCapabilities.java
Comment (Jonathing) [inline src/main/java/net/lyof/sortilege/capabilities/ModCapabilities.java:1]: The way I wrote the capability for this PR is entirely in my style. I don't exactly know how you would write them since this mod doesn't have any in the first place. It probably isn't a big deal since it doesn't seem like you currently have plans to port the Forge version to 1.20.1, but I wanted to let you know regardless.

File: src/main/java/net/lyof/sortilege/utils/XPHelper.java [hunk 1]
```diff
@@ -47,13 +48,29 @@ public static int getTotalxp(int level, float progress, ServerLevel server) {
...
+        EntityXpStorage.ifPresent(entity, storage -> storage.setXp(0));
+    }
+
+    public static void setSavedXp(LivingEntity entity, int xp) {
+        EntityXpStorage.ifPresent(entity, storage -> storage.setXp(xp));
+    }
+
+    public static void setSavedXp(LivingEntity entity, int xp, boolean onlyIfZero) {
+        EntityXpStorage.ifPresent(entity, storage -> storage.setXp(xp, onlyIfZero));
+    }
```
Comment (Jonathing) [inline src/main/java/net/lyof/sortilege/utils/XPHelper.java:72]: There were a couple of spots in `ModEvents` where you used `XPHelper.XP_STATS.putIfAbsent()`, which wouldn't have replaced the original value if there was one already there. I don't know if this is a bug on your part, but just in case, this parameter `onlyIfZero` mimics the `putIfAbsent` behavior of the old code.

**Review by Jonathing — COMMENTED** [review]
Here are some additional comments on some of my implementation details.

**Comment by Jonathing** [comment]
I've added a commit that follows up on #21, adding back in a field and methods that I previously deleted. I've marked them as deprecated for removal, but just in case any weird mods happen to be using them, they'll be around and do what they're supposed to (except for the field, that now stays empty).
